### ISSUE TITLE
Foot

### ISSUE THREAD

**Issue by Muvkina** [Himmalerin/kiss-wayland#2]
I've recently started using wayland. I am using this repo everything is working except in foot the text is really close together and garbeled. I haven't found this issue else where so thought you may have some insight.

**Comment by sincetheflood** [comment]
It's because whatever foot picks up by default isn't monospaced, I needed to make a config file and set the font to solve that issue. Just placing
```
font=Source Code Pro Semibold:size=14
```
in `.config/footrc` (adjusting to the name of your font) should work fine but you might want to take a look at the [full config](https://codeberg.org/dnkl/foot/src/branch/master/foot.ini) (which is also at `/usr/share/foot/footrc`) file as well.

Not sure what the best solution for avoiding future confusion, maybe putting a note about copying the default config into your home directory and modifying it in the post-install?

**Comment by Muvkina** [comment]
That worked thank you! And yes a post install script I believe would work best. Perhaps:

```
#!/bin/sh

echo ##########################
echo You must set a font in .config/footrc 
or copy the default config
echo ##########################
```

**Comment by dilyn-corner** [comment]
Note that footrc is deprecated and $HOME/.config/foot/foot.ini is the new default. 

Also, [foot dev recommends PGO](https://github.com/dilyn-corner/KISS-me/tree/master/extra/foot)

**Comment by Muvkina** [comment]
$HOME/.config/foot/foot.ini does not work for me. Is it master only?

**Comment by sincetheflood** [comment]
> Note that footrc is deprecated and $HOME/.config/foot/foot.ini is the new default.

My KISS system is dead for the moment but once everything is working again I'll check if it works for me and use that location instead.

> Also, [foot dev recommends PGO](https://github.com/dilyn-corner/KISS-me/tree/master/extra/foot)

I remember seeing that when I was making the build file for this repo but I skipped over it for the sake of simplicity, do you know if it makes a noticeable difference in anything? (build times/run speed/capabilities/whatever)

> $HOME/.config/foot/foot.ini does not work for me. Is it master only?

From a brief check I think so, it looks like checking for ~/.config/foot/foot.ini was added [in this commit](https://codeberg.org/dnkl/foot/commit/6dbd87016fc9f86c1681c3c438dbaeb7065b370b) two weeks ago and the last release was a month ago.

**Comment by dylanaraps** [comment]
You could set the default to 'monospace' I believe. It should then pick the default monospace font.

**Comment by dilyn-corner** [comment]
Yes sorry, that should say is being and not has been - 1.5 will be released soon enough and there are a lot of changes going into it. 
As for PGO, it seems to make at least some kind of difference. The hard part is that you need a running Wayland session to build it, so you end up building foot 4 times (once to get a terminal emulator, and 3 times for PGO in a Wayland session).

**Comment by sincetheflood** [comment]
I don't think I want to put users through that by default, maybe a foot-pgo package? To let them choose the benefits of PGO or simple building.
