### ISSUE TITLE
Firefox Segfault

### ISSUE THREAD

**Issue by Muvkina** [Himmalerin/kiss-wayland#3]
Sorry for all of this issues but I just finished compiling firefox and it seems to segfault when starting any idea on why? Or should I report a bug to firefox. Using gdb it's segfaulting at setjmp() from /lib/ld-musl-x86_64.so.1

**Comment by Muvkina** [comment]
My bad this is also just user error perhaps another post-install script? I needed to add --no-remote

**Comment by sincetheflood** [comment]
Yeah Firefox needs --no-remote, I should add a post-install mentioning that, or maybe a separate package that contains a shell script (and maybe a .desktop file) to handle all that for you? I've been using an alias to do it:
```
ffx='MOZ_ENABLE_WAYLAND=1 vblank_mode=0 OZ_WEBRENDER=1 MOZ_ACCELERATED=1 firefox --no-remote'
```

**Comment by Muvkina** [comment]
Mine probably wasn't best solution but I created a script in /usr/bin called flrefox-wayland that does the same thing.
